networks:
  docker-mudblazor:
    external: false

services:
  docker-mudblazor:
    image: ivoraedts/hello-docker-mudblazor:latest
    depends_on:
      postgres: 
        condition: service_healthy
        restart: true
    networks:
      - docker-mudblazor
    volumes:
     # - /volume1/docker/hello-docker-mudblazor/data:/app/data
      - ./docker/mudblazor:/app/data
      - ./docker/https:/app/https:ro
    ports:
      # <Host Port>:<Container Port>
      - "3080:8080"
      - "3443:8081"
    environment:
      # Connection string for the database (overrides appsettings.json)
      ConnectionStrings__MudBlazorDatabase: "Host=postgres:5432; Database=SomeTestDatabase; Username=user-name; Password=strong-password"
      S3__ServiceURL: "http://minio:9000"
      # Tell the app that HTTPS is on the external port 3443
      ASPNETCORE_HTTPS_PORT: 3443
      # Other configurable parameters can go here
      ASPNETCORE_ENVIRONMENT: Production

  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d SomeTestDatabase"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    container_name: docker-mudblazor.postgres
    #command: postgres -c max_connections=100
    volumes:  
    # This fix applies to version 18 and later. before it could mount to /var/lib/postgresql/data
    # This fix applies to version 18 and later: mount to /var/lib/postgresql/docker works, but does not persist
      - ./docker/pgdata:/var/lib/postgresql
    networks:
      - docker-mudblazor
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    ports:
      # <Host Port>:<Container Port>
      - "5432:5432"     

  minio:
    image: minio/minio:latest
    container_name: docker-mudblazor.minio
    networks:
      - docker-mudblazor
    volumes:
      - ./docker/minio/data:/data
    ports:
      # MinIO API
      - "9000:9000"
      # MinIO Web Console
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server /data --console-address ":9001"
    
  minio-init:
    image: minio/mc:latest
    container_name: docker-mudblazor.minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/calendar-events --ignore-existing;
      /usr/bin/mc anonymous set public myminio/calendar-events;
      exit 0;
      "
    networks:
      - docker-mudblazor

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: docker-mudblazor.pgadmin
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    networks:
      - docker-mudblazor
    ports:
      # <Host Port>:<Container Port>
      - "5050:80"

