networks:
  docker-mudblazor:
    external: false

services:
  docker-mudblazor:
    build:
      context: .
      dockerfile: MyApplication/Dockerfile
    networks:
      - docker-mudblazor
    volumes:
     # - /volume1/docker/hello-docker-mudblazor/data:/app/data
      - ./docker/mudblazor:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3080:8080"
      - "3081:8081"
