networks:
  docker-mudblazor:
    external: false

services:
  docker-mudblazor:
    image: ivoraedts/hello-docker-mudblazor:latest
    depends_on:
      postgres: 
        condition: service_healthy
        restart: true
    networks:
      - docker-mudblazor
    volumes:
     # - /volume1/docker/hello-docker-mudblazor/data:/app/data
      - ./docker/mudblazor:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3080:8080"
      - "3081:8081"
    environment:
      # Connection string for the database (overrides appsettings.json)
      ConnectionStrings__MudBlazorDatabase: "Host=postgres:5432; Database=SomeTestDatabase; Username=user-name; Password=strong-password"
      # Other configurable parameters can go here
      ASPNETCORE_ENVIRONMENT: Production

  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d SomeTestDatabase"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    container_name: docker-mudblazor.postgres
    #command: postgres -c max_connections=100
    volumes:  
    # This fix applies to version 18 and later. before it could mount to /var/lib/postgresql/data
    # This fix applies to version 18 and later: mount to /var/lib/postgresql/docker works, but does not persist
      - ./docker/pgdata:/var/lib/postgresql
    networks:
      - docker-mudblazor
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    ports:
      # <Host Port>:<Container Port>
      - "1234:5432"   

  adminer:
    image: adminer:latest
    container_name: docker-mudblazor.adminer    
    networks:
      - docker-mudblazor
    ports:
      # <Host Port>:<Container Port>
      - "8080:8080"